name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@aa39e02762e637db5f5ff81c6ef2a720bafef418"
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "Auto merge pull request #{pullRequest.number} {pullRequest.title}"
          MERGE_DELETE_BRANCH: true
